### PR TITLE
Add configuration to allow overriding the encoding method.

### PR DESCRIPTION
**Pull request by FabienChaynes**
This PR is related to #22.
It is obviously missing some specs and documentation, which I will add once we'll agree on the implementation.

It adds a `Configuration` object with an `@encoding_method` variable.

This variable will receive a `Proc` and will default to the `::URI.encode_www_form` method. If the variable is set, the `Proc` should expect a single argument responding to `#to_h` and return a string of the encoded hash.
It'd allow users to override the method encoding data in [HTTP::FormData::Urlencoded#initialize](https://github.com/httprb/form_data/blob/e938a40c0a8acc3f19792b085b77ddafc649581e/lib/http/form_data/urlencoded.rb#L16).

An example of the usage could be:
```ruby
HTTP::FormData.configure do |config|
  custom_encode_www_form = lambda do |enum|
    unescaped_chars = /[^a-z0-9\-\.\_\~]/i
    enum.map do |k, v|
      if v.nil?
        ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
      elsif v.respond_to?(:to_ary)
        v.to_ary.map do |w|
          str = ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
          unless w.nil?
            str << '='
            str << ::URI::DEFAULT_PARSER.escape(w.to_s, unescaped_chars)
          end
        end.join('&')
      else
        str = ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
        str << '='
        str << ::URI::DEFAULT_PARSER.escape(v.to_s, unescaped_chars)
      end
    end.join('&')
  end

  config.encoding_method = custom_encode_www_form
end
```

### CODE REVIEW

**Comment by FabienChaynes** [comment]
I removed the configuration in [the first commit](https://github.com/httprb/form_data/pull/23/commits/0b7edc5fedc8b60864b0de5ee56d94f5b373f654) and allowed `Urlencoded` to receive the encoder at initialization in [the second one](https://github.com/httprb/form_data/pull/23/commits/74ecde712954aa3c49b9292074e00e6da2b23d55).
Now it will allow a simpler monkey patching along the lines of:
```ruby
require "uri"

module HTTP
  module FormData
    def self.encoder
      lambda do |enum|
        unescaped_chars = /[^a-z0-9\-\.\_\~]/i
        enum.map do |k, v|
          if v.nil?
            ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
          elsif v.respond_to?(:to_ary)
            v.to_ary.map do |w|
              str = ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
              unless w.nil?
                str << '='
                str << ::URI::DEFAULT_PARSER.escape(w.to_s, unescaped_chars)
              end
            end.join('&')
          else
            str = ::URI::DEFAULT_PARSER.escape(k.to_s, unescaped_chars)
            str << '='
            str << ::URI::DEFAULT_PARSER.escape(v.to_s, unescaped_chars)
          end
        end.join('&')
      end
    end
  end
end
```

I'm not a huge fan of this solution though :confused:
Do you have something else in mind to customize this without a configuration object?

**Comment by FabienChaynes** [comment]
Re reading your comment, maybe you were just talking about exposing the encoder without wrapping it inside a `Configuration` object (which I did in d7a2c3f).
This way it'd be used like this:
```ruby
HTTP::FormData.encoder = lambda do |enum|
  # ...
end
```

**Comment by ixti** [comment]
I have changed this code a bit and merged this PR as https://github.com/httprb/form_data/commit/3bf2e834f63f03af305eb2e3ade6fabe89c73963

So basically I have moved away from the idea of having per-form encoder (at least for now). And exposed encoder on Urlencoded class. Meaning one can override default implementation with:

``` ruby
HTTP::FormData::Urlencoded.encoder = lambda { |data| ... }
```

**Comment by ixti** [comment]
Thank you!

**Comment by FabienChaynes** [comment]
Great, thanks!

**Comment by ixti** [comment]
Released as v2.1.1

**Pull request closed without merging**
